name: Python Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
   
    steps:
    - name: Set up Python
      uses: actions/checkout@v4
    - name: setup
      

    - name: setup python
      uses: actions/setup-python@v3
      with:
         python-version: "3.x"
         cache: "pip"
      env:
         AGENT_TOOLSDIRECTORY: /opt/hostedtoolache

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python-headless numpy

    - name: Run Python script
      run: python test.py
